language: node_js
node_js:
- "8.4.0"
sudo: required
cache:
  directories:
    - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script: 
- docker build -t coca1719/se234-lab11-client .
- docker push coca1719/se234-lab11-client

service: docker
